
### Get list
GET http://localhost:3000/users



### create
POST http://localhost:3000/users
Content-Type: application/json

{
    "username": "qodir",
    "email": "nurfianqodir@gmail.com",
    "firstName": "Nurfian",
    "password": "secretpassword"
}


### Login
POST http://localhost:3000/auth
Content-Type: application/json

{
    "username": "qodir",
    "password": "secretpassword"
}


### Logout
DELETE  http://localhost:3000/auth


### get profile
GET  http://localhost:3000/users/profile/gPi_CnnKlR


### get me
GET  http://localhost:3000/users/me


### delete me
DELETE  http://localhost:3000/users/me


### Update me
PATCH  http://localhost:3000/users/me
Content-Type: application/json

{
    "firstName": "Fuyun",
    "lastName": "Qodar"
}


###
PATCH  http://localhost:3000/users/me/update-unique
Content-Type: application/json

{
    "email": "fuyun@gmail.com",
    "username": "fuyun"
}


###
PATCH  http://localhost:3000/users/me/update-password
Content-Type: application/json

{
    "password" : "secretbang"
}